package com.data_merchants.finito.controller;

import com.data_merchants.finito.dto.MealPlanSaveRequest;
import com.data_merchants.finito.model.MealPlan;
import com.data_merchants.finito.service.MealPlanService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/meals")
@RequiredArgsConstructor
@CrossOrigin(origins = "*")
@Tag(name = "Meal Planning Tool", description = "Saves meal plans generated by the AI.")
public class MealPlanController {

    private final MealPlanService planService;

    @PostMapping("/save")
    @Operation(summary = "Save Generated Meal Plan", operationId = "saveMealPlan", description = "Call this AFTER you (the AI Agent) have generated a meal plan. This saves it to the user's dashboard. The plan content should be in markdown format with meal details, macros, and timing.")
    public ResponseEntity<MealPlan> savePlan(
            @RequestHeader(value = "X-User-Id", defaultValue = "477565737444656661756c7455736572") String headerUserId,
            @RequestBody MealPlanSaveRequest request) {

        // Prioritize the body param if the user provided it (as per their
        // documentation)
        String userId = headerUserId;
        if (request.headerXUserId() != null && !request.headerXUserId().isBlank()) {
            userId = request.headerXUserId();
        }

        return ResponseEntity.ok(planService.saveAIPlan(userId, request));
    }

    @GetMapping("/current")
    @Operation(summary = "Get Active Meal Plan", operationId = "getCurrentMealPlan", description = "Retrieves the user's current active meal plan. Returns the most recently saved plan for the user, or null if no plan exists.")
    public ResponseEntity<MealPlan> getCurrentPlan(
            @RequestHeader(value = "X-User-Id", defaultValue = "477565737444656661756c7455736572") String userId) {
        return ResponseEntity.ok(planService.getCurrentPlan(userId));
    }
}