package com.data_merchants.finito.controller;

import com.data_merchants.finito.dto.MealPlanSaveRequest;
import com.data_merchants.finito.model.MealPlan;
import com.data_merchants.finito.service.MealPlanService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/meals")
@RequiredArgsConstructor
@CrossOrigin(origins = "*")
@Tag(name = "Meal Planning Tool", description = "Saves meal plans generated by the AI.")
public class MealPlanController {

    private final MealPlanService planService;

    @PostMapping("/save")
    @Operation(summary = "Save Generated Plan", description = "Call this AFTER you (the Agent) have generated a meal plan text. This saves it to the user's dashboard.")
    public ResponseEntity<MealPlan> savePlan(
            @RequestHeader(value = "X-User-Id", defaultValue = "Alice") String userId,
            @RequestBody MealPlanSaveRequest request) {
        return ResponseEntity.ok(planService.saveAIPlan(userId, request));
    }

    @GetMapping("/current")
    @Operation(summary = "Get Active Plan", description = "Retrieves the user's current active meal plan.")
    public ResponseEntity<MealPlan> getCurrentPlan(
            @RequestHeader(value = "X-User-Id", defaultValue = "Alice") String userId) {
        return ResponseEntity.ok(planService.getCurrentPlan(userId));
    }
}