package com.data_merchants.finito.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

public record MealPlanSaveRequest(
                String goalType, // e.g. "High Protein"
                @JsonProperty("planContent") String planContent, // The full text generated by the AI
                @JsonProperty("header_X-User-Id") String headerXUserId // Optional override
) {
}