package com.data_merchants.finito.dto;

public record WorkoutPlanSaveRequest(
                String goal, // e.g. "Hypertrophy"
                String planContent // The full markdown text generated by the AI
) {
}